# CI pipeline definition
# See: https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
  autoCancel: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
    - master
  always: true

variables:
# library variable groups
- group: 'build-tools'
# environment variables
- name: DOTNET_CLI_TELEMETRY_OPTOUT
  value: 1
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
# common task variables
- name: 'BuildConfiguration'
  value: 'Debug'
- name: 'SolutionFile'
  value: 'MongoDb.Atlas.Client.sln'
- name: 'TestProjects'
  value: '**/*[Tt]ests/*.csproj'
# tool variables (Sonar)
- name: 'sonar.project.name'
  value: 'Kirrk Backend Api'
- name: 'sonar.project.key'
  value: 'kirrk.backend.api'

pool:
  # code coverage generation only works on Windows for the moment
  vmImage: 'windows-latest'

steps:
- task: SonarQubePrepare@4
  displayName: 'Prepare code analysis'
  inputs:
    SonarQube: '$(sonar.instance)'
    scannerMode: 'MSBuild'
    projectKey: '$(sonar.project.key)'
    projectName: '$(sonar.project.name)'

- task: DotNetCoreCLI@2
  displayName: 'Build the .NET solution'
  inputs:
    command: 'build'
    projects: $(SolutionFile)
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run the .NET test projects'
  inputs:
    command: 'test'
    projects: $(TestProjects)
    arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

- task: SonarQubeAnalyze@4
  displayName: 'Analyze the code with Sonar'

- task: SonarQubePublish@4
  displayName: 'Publish the code analysis results'
  inputs:
    pollingTimeoutSec: '300'
