# CI pipeline definition
# See: https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: mongodbatlasdotnetclientci
    source: mongodb-atlas-dotnet-client-ci
    trigger:
      branches:
        include:
        - master

trigger: none

pr: none

variables:
# library variable groups
- group: 'build-tools'
# environment variables
- name: DOTNET_CLI_TELEMETRY_OPTOUT
  value: 1
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
# common task variables
- name: 'BuildConfiguration'
  value: 'Release'
- name: 'SolutionFile'
  value: 'MongoDb.Atlas.Client.sln'
# tool variables (NuGet)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build the .NET solution'
  inputs:
    command: 'build'
    projects: $(SolutionFile)
    arguments: '-c $(BuildConfiguration)'
